### ISSUE TITLE
Thoughts on Browserify vs Duo

### ISSUE THREAD

**Issue by kvnneff** [matthewmueller/ama#11]
I think you said somewhere that Component really changed the way you approach front-end work and it did the same for me, and I would also say the coding style put forth by yourself and other major contributors to the Component ecosystem (like @yields, @jonathanong, @dominicbarnes etc) also really influenced my style as well and, essentially, beyond StackOverflow and a few tutorials nearly all of my coding education has come from reading the source code of your modules and the ones written by others I mentioned above.  I always found them easy-to-read, well-documented, and small and succinct.

So I follow a lot of those contributors here on github and I've noticed neither you nor @yields has contributed to Duo in some time, and every so often I see you star a Browserify module.

I wanted to ask if you are using Browserify more often now, and if you are, what are your reasons for doing so?  Are you planning to continue contributing to Duo or do you feel done with that project?  I'm not looking for a "which is better" or "tell me which one I should use", just your thought process on how you decide which bundler to use these days :)

I ask specifically because I love Duo and it's a no-brainer on personal projects, but I encounter hang-ups every so often that cause me to question whether I should just use Browserify full-time: if I find full-time work it's almost guaranteed that team will be using Browserify, Browserify currently plays better with npm and node.js, and Duo currently has no support for modules not hosted on Github.

**Comment by matthewmueller** [comment]
Good and challenging question. I've been meaning to write a blog post on this. Let me start with a bit of context.

Duo was by far the largest and most challenging open source project I've taken on. Before launching (open sourcing the repo) there were thousands of download on the NPM package directly. I started Duo because I felt like Component development was headed in the wrong direction and the Browserify community wasn't really addressing how to bundle anything other than JS assets together. 

The landscape has changed though. React, webpack, npm and browserify are all thinking about how to encapsulate all the various assets into modules. Now we have lots of folks thinking about this stuff which is great for the JS community at large. 

In our latest app, we are trying out Browserify. I was re-introduced to Browserify by @defunctzombie and have been impressed at how easy the package manager gets out of the way. With Duo we found ourselves constantly opening PRs to add `component.json`'s or forking projects. That was fine when the Component community was larger, but it's been shrinking lately.

There are also some big bugs in Duo that I just do not have the time to solve. I'm part of a 4-person startup and it's just not economical right now to spend my time working on an open source project as demanding as Duo.

With that said, I'm really pushing for Duo, albeit from the sidelines lately. @dominicbarnes and @stephenmathieson have been doing an incredible job keeping the project alive and have addressed some big issues with it lately (like the caching bugs). There's a good chance I'll return to Duo soon :-)

---

With a better view of the differences, some sort of merger of the projects would yield the best of both worlds. Here are some things that the projects could learn from each other. Each bullet point represents an advantage that the project has over the alternative:

| Browserify | Duo |
| --- | --- |
| \- understands package.json | \- does incremental builds (w/o an external process) |
| \- separate install and build steps | \- better transform pipeline |
| \- the `browser` field | \- native CSS support (& any other asset) |
| \- shared bundles | \- much more intuitive codebase |

I can go into more detail if you'd like. Webpack is also impressive, but it's ridiculously cryptic. I'm waiting for someone to come along and write something on top of Webpack's API that makes it easier to understand for humans.

I hope this helps explain why I haven't been contributing lately. Honestly I feel like I've let a whole bunch of people down :-(. I just do not have the bandwidth right now to meet the demands needed to make the project competitive with the alternatives.

**Comment by kvnneff** [comment]
Thanks for the awesome response!  I definitely don't feel let down by you or anyone else working on Duo.  Up until recently I was employed full-time to code and personally I really didn't like continuing to work on side-projects after-hours.  There are plenty of other things I want to do and experience beyond coding so I don't think it's fair to fault anyone else for however many unpaid hours they might contribute to a free and open-source project.

Despite whatever shortcomings may exist I find Duo to be super intuitive and its handling of assets is unmatched by any of the other options.  Duo has a much smaller community and far fewer contributions from outside the core contributors but still stands on its own against the others.  Again, having discussions about which is better or whatnot aren't interesting to me, but if we evaluate Duo on its own it really is a great project that anyone can get up and running with within a matter of minutes.

It's just nice to know where things currently stand.  For instance I advocated for it at my last full-time job, even though we were required to keep all our code in a local Stash repository, because I thought Duo was on the verge of supporting providers other than github.  It worked out fine for that project because it was small and everything I needed was on github, but if I had had to require any private, local modules I would've had to have switched to Browserify.

In any case, I still think Duo is great at what it does and and very useable and if there are companies that feel disappointed with the results I think its mostly on them for not contributing money or work-hours.
