### ISSUE TITLE
What's the favorite module you've made and why?

### ISSUE THREAD

**Issue by sindresorhus** [matthewmueller/ama#5]

**Comment by matthewmueller** [comment]
Hmm, that's a tough one. I don't think I can pick one, but my favorite ones are modules that teach me something and turn out surprisingly well (terse, not a leaky abstraction).  Here's a few and why:
- [cheerio](http://github.com/cheeriojs/cheerio): this was one of my first modules. this module taught me that my code had actual value and encouraged me to continue honing my craft and get more involved in the community. 
- [duo](http://github.com/duojs/duo): duo was a fun one because it was the first time i deeply collaborated with someone across timezones. I would get a bunch of work done, go to bed, wake up with a bunch of updates from @yields. 
- [date](http://github.com/matthewmueller/date): date helped me learn about parsers and not be afraid to write my own DSLs
- [koa-bundle](https://github.com/koajs/bundle): not a lot of folks use this one, but it's middleware that pretty much solves asset bundling (via caching, etagging, minifying, etc.) using whatever build system you prefer. Dependent on koa for now though.
- [replace-text](https://github.com/automattic/replace-text): I like this one because it allows you replace arbitrary DOM nodes with other arbitrary DOM nodes and while the API turned out really well, the amount of effort it took to get to that point was immense. 

As I'm sure you can relate, there are many, many more that I like too. Building modules is quite addicting :-)

**Comment by sindresorhus** [comment]
:+1:
